#!/usr/bin/with-contenv bash
# ==============================================================================
# Start Recoll Web UI
# ==============================================================================

/usr/bin/recollindex -z
exec /usr/bin/recollindex -m -D
